global using WpfApp = System.Windows.Application;
global using Medior.Extensions;
global using Medior.Models.Messages;
global using Medior.Reactive;
global using Medior.Services;
global using Medior.Services.ScreenCapture;
global using CommunityToolkit.Mvvm.Messaging;
global using CommunityToolkit.Mvvm.Messaging.Messages;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;